# Generated by Django 4.2.7 on 2023-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Кртинка'),
            preserve_default=False,
        ),
    ]
