# Generated by Django 4.2.7 on 2024-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
